mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^flow/', include('polls.urls')),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/home/$', views.flowprjhome, name='flowprjhome'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/regist$', views.flowregist, name='flowprjregist'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/new/$', views.flow_create_question, name='myflow'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/index/$', views.flowindex, name='myflowindex'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/cur_user/$', views.flow_index_for_current_user, name='PrjIndexForCurUser'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/grpauthadmin/$', views.flow_grp_auth_admin, name='flowgrpauthadmin'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/exportdata/$', views.flow_export_excel, name='flowprjexport'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/muti__process/$', views.flow_muti_item_process, name='flow_muti_item_process'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/(?P<model_id>[0-9]+)/detail/$', views.myflowdetail, name='flowdetail'),
    url(r'^(?P<prj_name>[a-zA-Z0-9_]+)/(?P<model_id>[0-9]+)/detail/(?P<path_file>[^$]*)$', views.generic_down_load, name='flowgenericdownload'),
    url(r'^tmp/$', views.myflowprocess, name='myflowprocess'),
    url(r'^regist/$', views.flowregist, name='flowregist'),
    url(r'^login/$', views.flowlogin, name='flowlogin'),
    url(r'^logout/$', views.flowlogout, name='flowlogout'),
    url(r'^userinfo/$', views.flowuserinfo, name='flowuserinfo'),
    url(r'^down_help_doc/$', views.flow_file_download, name='down_help_doc'),
    url(r'^home/$', views.flowhome, name='flowhome')
]

mysite/polls/models.py
import django.utils.timezone as timezone
import datetime
from django.db import models
from django.utils import timezone
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import Group
# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
############################################################################################################################################################
class UserModel(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.EmailField(default="example@example.com")

class UserForm(ModelForm):
    class Meta:
        model = UserModel
        fields = '__all__'
        widgets = {
            'password': forms.PasswordInput()
        }
############################################################################################################################################################
#改进建议提取
class NameModel(models.Model):
    summary = models.CharField(max_length=200, verbose_name="概要")
    detail = models.CharField(max_length=5000, verbose_name="详细描述")
    current_process = models.CharField(max_length=5000, verbose_name="处理进展",default="##由改进实施人填写##")
    #viewer_advice = models.CharField(max_length=5000, verbose_name="评审人意见",default="##由评审人填写##")
    value = models.CharField(max_length=200, default="0", verbose_name="改进价值评估")
    reviewer = models.CharField(max_length=200, default="#提交人填写#", verbose_name="改进建议评审人")
    executor = models.CharField(max_length=200, default="#由建议评审人指派#", verbose_name="改进建议实施人")
    assigned_to   = models.CharField(max_length=200, default="", verbose_name="当前处理人(只读)")
    created_by = models.CharField(max_length=200, default="", verbose_name="创建人(只读)")
    curent_state = models.CharField(max_length=200, verbose_name="当前状态(只读)")

class NameForm(ModelForm):
    class Meta:
        model = NameModel
        fields = '__all__'
        widgets = {
            'summary' : forms.TextInput(attrs={'size':79}),
            'value' : forms.TextInput(attrs={'cols': 80, 'rows': 1}),
            'current_process' : forms.Textarea(attrs={'cols': 80, 'rows': 5}),
            #'viewer_advice' : forms.Textarea(attrs={'cols': 80, 'rows': 5}),
            'detail' : forms.Textarea(attrs={'cols': 80, 'rows': 5}),
            'assigned_to': forms.TextInput(attrs={'readonly': True,'size':20}),
            'created_by': forms.TextInput(attrs={'readonly': True}),
            'curent_state': forms.TextInput(attrs={'readonly': True}),
        }
helpmsg_imprvmt = [
    '【主干流程说明】:',
    '##{{环节，责任人}}##',
    '##<触发条件>##',
    '{{提交建议,创建人}}',
    '<提交评审>',
    '{{改进建议价值评审,改进建议评审人}}',
    '<指定实施人>',
    '{{改进建议实施,改建建议实施人}}',
    '<实施结果提交评审>',
    '{{实施结果评审,改进建议评审人}}',
    '<落地关闭>',
    '{{关闭}}'
]
############################################################################################################################################################
#实验室设备使用
class DeviceCardModel(models.Model):
    summary = models.CharField(max_length=200, verbose_name="设备描述")
    device_info = models.CharField(max_length=2000, verbose_name="设备信息", default="【归属小组】:")
    current_process = models.CharField(max_length=200, verbose_name="当前使用状态",default="##闲置OR使用##")
    occupied_by = models.CharField(max_length=200, default="#使用人更新#", verbose_name="设备使用人")
    assigned_to   = models.CharField(max_length=200, default="anyone", verbose_name="分配给(只读)")
    created_by = models.CharField(max_length=200, default="", verbose_name="创建人(只读)")
    curent_state = models.CharField(max_length=200, verbose_name="当前状态(只读)")

class DeviceCardForm(ModelForm):
    class Meta:
        model = DeviceCardModel
        fields = '__all__'
        exclude = []#['curent_state','created_by']
        widgets = {
            'summary' : forms.TextInput(attrs={'size':50}),
            'device_info':forms.Textarea(attrs={'cols': 52, 'rows': 5}),
            'current_process' : forms.TextInput(attrs={'readonly': True,'size':20}),
            'assigned_to': forms.TextInput(attrs={'readonly': True,'size':20}),
            'created_by': forms.TextInput(attrs={'readonly': True}),
            'curent_state': forms.TextInput(attrs={'readonly': True}),
        }
DeviceManageAuth = {
    '访问权限':'Visit',
    '使用权限':'Exec',
}
DeviceManageGrp = {
    '管理员群组':'AdminGrp',  #Must in this format:'中文名':'English name'
    '用户群组':'UserGrp',
    '注册用户群组':'RegisteredUserGrp'
}
############################################################################################################################################################
#捷安特售后保养
BYCLE_TYPES_CHOICES = (
    ('TCR',(
            ('TCR 圆点', 'TCR 圆点'),
            ('TCR 环意粉', 'TCR 环意粉'),
            ('TCR SL', 'TCR SL'),
            ('TCR Pro Disc', 'TCR Pro Disc'),
            ('TCR Pro Team', 'TCR Pro Team'),
            ('TCR Pro 0', 'TCR Pro 0'),
            ('TCR Pro 1', 'TCR Pro 1'),
            ('TCR ADV 1', 'TCR ADV 1'),
            ('TCR ADV 2', 'TCR ADV 2'),
            ('TCR ADV 3', 'TCR ADV 3'),
            ('TCR 6700', 'TCR 6700'),
            ('TCR 6300', 'TCR 6300'),
        )
    ),
    ('Propel', (
            ('Propel ADV 1', 'Propel ADV 1'),
            ('Propel ADV 2', 'Propel ADV 2'),
            ('Propel ADV 3', 'Propel ADV 3'),
        )
    ),
    ('XTC', (
            ('XTC ADV 1', 'XTC ADV 1'),
            ('XTC ADV 2', 'XTC ADV 2'),
            ('XTC ADV 3', 'XTC ADV 3'),
            ('XTC SLR', 'XTC SLR'),
            ('XTC 880', 'XTC 880'),
            ('XTC 860', 'XTC 860'),
            ('XTC 820', 'XTC 820'),
            ('XTC 800', 'XTC 800'),
        )
    ),
    ('ATX', (
            ('ATX 850', 'ATX 850'),
            ('ATX 700', 'ATX 700'),
            ('ATX 610', 'ATX 610'),
        )
    ),
)
CHOICE_ORDER_TYPES = (
    ('维修调试','维修调试'),
    ('例行保养','例行保养'),
)
class GiantMaintainModel(models.Model):
    summary = models.CharField(max_length=200, verbose_name="QQ昵称")
    weixin  = models.CharField(max_length=200, verbose_name="微信号")
    custom_name = models.CharField(max_length=200, verbose_name="真实姓名", default='##请在此输入真实姓名##')
    device_info = models.CharField(max_length=2000, verbose_name="车辆型号", choices=BYCLE_TYPES_CHOICES)
    order_type = models.CharField(max_length=2000, verbose_name="预约类型", choices=CHOICE_ORDER_TYPES)
    buy_date = models.DateField(max_length=2000, verbose_name="购买日期", default=timezone.now)
    order_date = models.DateField(max_length=2000, verbose_name="预约日期", default=timezone.now,help_text='填写预约的进行维保的日期')
    more_info = models.CharField(max_length=9000, verbose_name="备注",default="##简要描述需要处理的单车问题##")
    assigned_to   = models.CharField(max_length=200, default="anyone", verbose_name="分配给(只读)")
    created_by = models.CharField(max_length=200, default="", verbose_name="创建人(只读)")
    curent_state = models.CharField(max_length=200, verbose_name="当前状态(只读)")

class GiantMaintainForm(ModelForm):
    class Meta:
        model = GiantMaintainModel
        fields = '__all__'
        exclude = []#['curent_state','created_by']
        widgets = {
            'summary' : forms.TextInput(attrs={'size':50}),
            'weixin' : forms.TextInput(attrs={'size':50}),
            'custom_name' : forms.TextInput(attrs={'size':50}),
            'more_info' : forms.Textarea(attrs={'cols': 50, 'rows': 5}),
            'assigned_to': forms.TextInput(attrs={'readonly': True,'size':20}),
            'created_by': forms.TextInput(attrs={'readonly': True}),
            'curent_state': forms.TextInput(attrs={'readonly': True}),
        }
GiantMaintainAuth = {
    'visit':{'role':['Creator','Administrator','Processor']},
}
GiantMaintainGrp = {
    '用户群组':'UserGrp',
    '注册用户群组':'RegisteredUserGrp'
}
############################################################################################################################################################
#上市保障问题跟踪
CHOICE_CUSTOMER_TYPE = (
    ('jinrong','金融'),
    ('dianli','电力'),
    ('nengyuan','能源'),
    ('guangdian','广电'),
    ('meizi','媒资'),
    ('tezhong','特种行业'),
    ('neibu','内部客户'),
    ('其他','其他'),
)

CHOICE_ISSUE_CLASS_1 = (
    ('软件','软件'),
    ('硬件','硬件'),
    ('结构','结构'),
    ('误操作','误操作'),
    ('配置','配置'),
    ('兼容性','兼容性'),
    ('沟通协作','沟通协作'),
)
CHOICE_ISSUE_LEVEL = (
    ('一级事故','一级事故'),
    ('二级事故','二级事故'),
    ('三级事故','三级事故'),
    ('一级ITR','一级ITR'),
    ('二级ITR','二级ITR'),
    ('三级ITR','三级ITR'),
    ('A级重大问题','A级重大问题'),
    ('B级重大问题','B级重大问题'),
    ('C级重大问题','C级重大问题'),
    ('一般问题','一般问题'),
)

CHOICE_ISSUE_CLASS_2 = (
    ('软件', (
            ('FC', 'FC'),
            ('SAS', 'SAS'),
            ('固件', '固件'),
            ('压缩', '压缩'),
        )
    ),
    ('硬件', (
            ('内存', '内存'),
            ('板卡', '板卡'),
            ('线缆', '线缆'),
        )
    ),
    ('误操作', '误操作'),
    ('结构', '结构'),
    ('配置', '配置'),
    ('兼容性','兼容性'),
    ('沟通协作', '沟通协作'),
)


RESPONSE_FIELD_CHOICES = (
    ('软件', (
            ('FC', 'FC'),
            ('SAS', 'SAS'),
            ('固件', '固件'),
            ('压缩', '压缩'),
        )
    ),
    ('硬件', (
            ('内存', '内存'),
            ('板卡', '板卡'),
            ('线缆', '线缆'),
        )
    ),
)
class IssueTrackModel(models.Model):
    summary = models.CharField(max_length=200, verbose_name="概要", default="【20170101】XX局点XX设备发生XX问题")
    detail = models.CharField(max_length=5000, verbose_name="详细描述")

mysite/polls/forms.py
from django import forms
from django.forms import ModelForm

class NameForm2(forms.Form):
    summary = forms.CharField(label='事件概要', max_length=100)
    priority = forms.CharField(label='重要程度', max_length=100)
    urgency = forms.CharField(label='紧急程度', max_length=100)
    current_process = forms.CharField(label='当前进展', widget=forms.Textarea)
    deadline = forms.CharField(label='截止时间', max_length=100)
    curent_state = forms.CharField(label='当前状态', max_length=100)

class NameForm1(forms.Form):
    summary = forms.CharField(label='单车型号', max_length=100)
    priority = forms.CharField(label='购买时间', max_length=100)
    urgency = forms.CharField(label='车友姓名', max_length=100)
    deadline = forms.CharField(label='车友电话', max_length=100)
    current_process = forms.CharField(label='保养记录', widget=forms.Textarea)
    curent_state = forms.CharField(label='当前状态', max_length=100)

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/flowdetail.html
{% load static %}


<style type="text/css">
html,body,.parent{height: 100%; overflow: hidden;}
        .top{position: absolute; top: 0; left: 0; right: 0; height: 0; background-color: #F3F3FA; height: 50px;}
        .left{position: absolute; top: 50px; left: 0;bottom: 50px; width: 75%; background-color: #E0E0E0;overflow:auto;}
        .right{position: absolute; top: 50px; left: 75%; right: 0; bottom: 50px; background-color: #FFFFCE; overflow: hidden;}
        .bottom{position: absolute; left: 0; right: 0; bottom: 0; height: 50px; background-color: #F3F3FA;}
</style>
<div class="parent">
    <div class="top">
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
        <p>【TaskSteper】积跬步，至千里</p>
    </div>
    <div class="left">

        <form enctype="multipart/form-data"  action="{% url 'polls:flowdetail' prj_name model_id %}" method="post" >
        <p>【当前项目】{{ PrjNameZh }}【ID】Item_{{ model_id }}</p>
        <table>
            {% csrf_token %}
            {% for field in form %}
                <!--<div class="fieldWrapper">-->
                <tr>
                    <td>【{{ field.label_tag }}】</td>
                    <td> {{ field }}</td>
                </tr>
                {% if field.help_text %}
                <tr><td></td><td>{{ field.help_text }}</td></tr>
                {% endif %}
                <!--</div>-->
            {% endfor %}
        </table>
        {% if trigger %}
            {% for elmt in trigger %}
                <input type="submit" value={{elmt}} name='trigger' />
            {% endfor %}
        {% endif %}
        </form>
        <li><a href="{% url 'polls:flowhome' %}">返回首页</a></li>
        <li><a href="{% url 'polls:flowprjhome' prj_name %}">返回项目首页</a></li>
    </div>
    <div class="right">
    </div>
    <div class="bottom">bottom</div>
</div>

mysite/polls/templates/polls/flowgrpauthadmin.html
<p><a href="{% url 'polls:flowprjexport' prj_name %}">导出数据</a></p>
<p>==============================================================================</p>
<form action="{% url 'polls:flowgrpauthadmin' prj_name %}" method="post">

<table>
    {% csrf_token %}
    {% for field in AddAuthToGrpForm %}
        <!--<div class="fieldWrapper">-->
            <tr>
                <td>{{ field.label_tag }}</td><td> {{ field }}</td>
                    {% if field.help_text %}
                       <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
            </tr>
        <!--</div>-->
    {% endfor %}
</table>
    <input type="submit" value="为群组添加权限" name='trigger'/>
    <input type="submit" value="从群组删除权限" name='trigger'/>

</form>
<p>==============================================================================</p>
<form action="{% url 'polls:flowgrpauthadmin' prj_name %}" method="post">

<table>
    {% csrf_token %}
    {% for field in AddUserToGrpForm %}
        <!--<div class="fieldWrapper">-->
            <tr><td>{{ field.label_tag }}</td><td> {{ field }}<td></tr>
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        <!--</div>-->
    {% endfor %}
</table>
    <input type="submit" value="添加用户到群组" name='trigger'/>
    <input type="submit" value="从群组移除用户" name='trigger'/>

</form>
<p>==============================================================================</p>
<li><a href="{% url 'polls:flowhome' %}">返回首页</a></li>
<li><a href="{% url 'polls:flowprjhome' prj_name %}">返回项目首页</a></li>

mysite/polls/templates/polls/flowhome.html
{% load static %}


<style type="text/css">
html,body,.parent{height: 100%; overflow: hidden;}
        .top{position: absolute; top: 0; left: 0; right: 0; height: 0; background-color: #F3F3FA; height: 50px;}
        .left{position: absolute; top: 50px; left: 0;bottom: 50px; width: 75%; background-color: #E0E0E0;overflow:auto;}
        .right{position: absolute; top: 50px; left: 75%; right: 0; bottom: 50px; background-color: #FFFFCE; overflow: hidden;}
        .bottom{position: absolute; left: 0; right: 0; bottom: 0; height: 50px; background-color: #F3F3FA;}
</style>
<div class="parent">
    <div class="top">
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
        <p>【TaskSteper】积跬步，至千里</p>
    </div>
    <div class="left">
        {% if prj_list %}
            <table>
                {% csrf_token %}
                {% if username %}
                    <tr>
                        <td>Hello, {{ username }}</td>
                        <td>【<a href="{% url 'polls:flowlogout' %}">注销</a>】</td>
                        <td>【<a href="{% url 'polls:flowuserinfo' %}">个人信息</a>】</td>
                    </tr>
                {% else %}
                    <ol>
                        <li>请先<a href="{% url 'polls:flowlogin' %}">登录</a>；</li>
                        <li>如果没有账号，请先在所需项目注册，并联系管理员添加权限</li>
                    </ol>
                {% endif %}
                <tr><td>项目名称</td><td>待办数目</td><td>权限管理</td><td>创建条目</td><td>注册项目用户</td></tr>
                {% for cur_prj in prj_list %}
                    <tr>
                        <td>♦<a href="{% url 'polls:flowprjhome' cur_prj.prj_name %}">{{ cur_prj.prj_name_zh }}</a></td>
                        <td>[{{ cur_prj.assigned_count }}]</td>
                        <td><a href="{% url 'polls:flowgrpauthadmin' cur_prj.prj_name %}">管理</a></td>
                        <td><a href="{% url 'polls:myflow' cur_prj.prj_name %}">创建</a></td>
                        <td><a href="{% url 'polls:flowprjregist' cur_prj.prj_name %}">注册</a></td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p>请先登录；如果没有账号，请先注册</p>
            <li><a href="{% url 'polls:flowregist' %}">注册</a></li>
            <li><a href="{% url 'polls:flowlogin' %}">登录</a></li>
        {% endif %}
    </div>
    <div class="right">
        【帮助信息】:如果计划使用某个项目，请先在该项目注册，然后联系项目管理员添加权限；</br>
         &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp如果项目归属于项目群，则只需要在项目群中的一个项目中注册，使用具体项目时联系管理员开通权限，
            无需在项目群的每个项目注册(暂时不支持项目群功能,等后续实现)</br>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp更多信息请参考:<a href="{% url 'polls:down_help_doc' %}">帮助文档</a></br>
    </div>
    <div class="bottom">bottom</div>
</div>

mysite/polls/templates/polls/flowindex.html
<p>【TaskSteper】积跬步，至千里</p>
{% if username %}
    <table>
        <tr><td>Hello, {{ username }}</td><td>【<a href="{% url 'polls:flowlogout' %}">注销</a>】</td></tr>
    </table>
    {% if latest_namemodel_list %}
      <form action="{% url 'polls:flow_muti_item_process' prj_name %}" method="post">
        <table>
        {% csrf_token %}
        <tr>
            <td>选中</td>
            <td align="center">ID</td><td>概要</td><td>当前状态</td><td>当前处理人</td><td>报告人</td>
        </tr>
        {% for namemodel in latest_namemodel_list %}
            <tr>
                <td><input type="checkbox" value={{ namemodel.id }} name="check_box_list"/></td>
                <td><a href="{% url 'polls:flowdetail' prj_name namemodel.id %}">Item_{{ namemodel.id }}</a></td>
                <td>{{ namemodel.summary }}</td>
                <td>{{ namemodel.curent_state }}</td>
                <td>{{ namemodel.assigned_to }}</td>
                <td>{{ namemodel.created_by }}</td>
            </tr>
        {% endfor %}
        </table>
        <input type="submit" value="删除">
      </form>
    {% else %}
        <p>No items are available.</p>
    {% endif %}
{% else %}
    <p>请先返回首页,使用您的账号登录系统</p>
{% endif %}
<li><a href="{% url 'polls:flowhome' %}">返回首页</a></li>

mysite/polls/templates/polls/flowlogin.html
<form action="{% url 'polls:flowlogin' %}" method="post">

<table>
    {% csrf_token %}
    {% for field in form %}
        <!--<div class="fieldWrapper">-->
            <tr><td>{{ field.label_tag }}</td><td> {{ field }}<td></tr>
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        <!--</div>-->
    {% endfor %}
</table>
    <input type="submit" value="登录" />

</form>
<li><a href="{% url 'polls:flowhome' %}">返回首页</a></li>

mysite/polls/templates/polls/flowprjhome.html
{% load static %}

<style type="text/css">
html,body,.parent{height: 100%; overflow: hidden;}
        .top{position: absolute; top: 0; left: 0; right: 0; height: 0; background-color: #F3F3FA; height: 130px;}
        .left{position: absolute; top: 130px; left: 0;bottom: 50px; width: 75%; background-color: #E0E0E0;overflow:auto;}
        .right{position: absolute; top: 130px; left: 75%; right: 0; bottom: 50px; background-color: #FFFFCE; overflow: auto;line-height:22px}
        .bottom{position: absolute; left: 0; right: 0; bottom: 0; height: 50px; background-color: #F3F3FA;}
</style>
<div class="parent">
    <div class="top">
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
        <ul>
            <li>当前项目：{{ prj_name_zh }}</li>
            <li><a href="{% url 'polls:myflow' prj_name %}">创建条目</a></li>
            <li><a href="{% url 'polls:myflowindex' prj_name %}">所有条目</a></li>
            <li><a href="{% url 'polls:flowhome' %}">返回首页</a></li>
        </ul>
    </div>
    <div class="left">
        {% if obj_list %}
            <table>
            <tr><td style="width:7%;overflow:break;">待处理项:</td></tr>
            <tr><td>ID</td><td>概要</td><td>当前状态</td><td>当前处理人</td><td>报告人</td></tr>
            {% for obj_item in obj_list %}
                <tr>
                    <td><a href="{% url 'polls:flowdetail' prj_name obj_item.id %}">Item_{{ obj_item.id }}</a></td>
                    <td style="width:55%;overflow:break;">{{ obj_item.summary }}</td>
                    <td>{{ obj_item.curent_state }}</td>
                    <td>{{ obj_item.assigned_to }}</td>
                    <td>{{ obj_item.created_by }}</td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>待处理条目[0]</p>
        {% endif %}
    </div>
    <div class="right">
        {% if help_msg %}
            {% for item in help_msg %}
                {{ item }}</br>
            {% endfor %}
        {% endif %}
    </div>
    <div class="bottom">bottom</div>
</div>

mysite/polls/templates/polls/flowregist.html
{% if prj_name %}
    <form action="{% url 'polls:flowprjregist' prj_name %}" method="post">
{% else %}
    <form action="{% url 'polls:flowregist' %}" method="post">
{% endif %}

<table>
    {% csrf_token %}
    {% for field in form %}
        <!--<div class="fieldWrapper">-->
            <tr><td>{{ field.label_tag }}</td><td> {{ field }}<td></tr>
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        <!--</div>-->
    {% endfor %}
</table>
    <input type="submit" value="注册" />

</form>
<li><a href="{% url 'polls:flowhome' %}">返回首页</a></li>

mysite/polls/templates/polls/name.html
<form  enctype="multipart/form-data" action="{% url 'polls:myflow' prj_name%}" method="post">
    <table>
        {% csrf_token %}
        <tr><td>当前项目:</td><td>{{ PrjNameZh }}</td><tr>
        {% for field in form %}
            <!--<div class="fieldWrapper">-->
            <tr>
                <td>【{{ field.label_tag }}】</td>
                <td> {{ field }} </td>
            </tr>
            {% if field.help_text %}
            <tr><td></td><td>{{ field.help_text|safe }}</td></tr>
            {% endif %}
            <!--</div>-->
        {% endfor %}
    </table>
    <input type="submit" value="创建" />
</form>
<li><a href="{% url 'polls:flowhome' %}">首页</a></li>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>